services:
  - type: web
    name: tts-booking-agent
    env: python
    plan: free
    runtime: python-3.10.13
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python app.py"
